### ISSUE TITLE
It's possible change OS to UBUNTU

### ISSUE THREAD

**Issue by francoataffarel** [jlesage/docker-jdownloader-2#88] opened 2021-12-28 01:42 UTC
Hello Sir,

i wanna mount a nfs in my network, or bind some nfs in my host to direct to a folder in container. But when i bind show me:

/tmp #  echo oi4 > /mnt/ps4/mnt/usb0/oi4
/bin/sh: can't create /mnt/ps4/mnt/usb0/oi4: Not supported

i realize that Alpine its not a good OS to do this, can u help me to change OS system to a ubuntu or debian ?

**Comment by jlesage** [comment] 2021-12-28 23:08
I don't think the problem is Alpine.  A lot of people are using NFS mount successfully with the container.
You need to mount the NFS on the host and then add a volume mapping to it when you create the container.

Can you share the `docker run` command you used to create the container ?

**Comment by jlesage** [comment] 2022-11-18 17:37
Closing this issue.  Please re-open if needed.

**Closed** 2022-11-18 18:55 UTC
