### ISSUE TITLE
the container always stop in arm64 (libreelec)

### ISSUE THREAD

**Issue by Sirfrancis17** [jlesage/docker-jdownloader-2#20] opened 2018-10-31 14:24 UTC
Is the conatiner always stop because the docker run in libreelec (arm64)?

thanks

**Comment by Turiok** [comment] 2020-02-14 19:28
Duplicate from #36

**Comment by Turiok** [comment] 2020-02-14 19:29
Duplicate of #36

**Comment by jlesage** [comment] 2022-11-18 19:06
Latest image now supports arm64.

**Closed by jlesage** 2022-11-18 19:06 UTC
