### ISSUE TITLE
Fatal Server Error

### ISSUE THREAD

**Issue by DaLeberkasPepi** [jlesage/docker-jdownloader-2#2] opened 2017-07-29 07:20 UTC
The WebUI of jDownloader 2 wasn't reachable at the morning when i tried to access it. 

The Log states this error multiple times:
```
(EE) Server is already active for display 0
If this server is no longer running, remove /tmp/.X0-lock
and start again.
(EE)
[services.d] x11vnc: waiting for xvfb to be ready...
[services.d] openbox: waiting for xvfb to be ready...
[services.d] app: waiting for openbox to be ready...
[services.d] xvfb: starting...
(EE)
Fatal server error:

(EE) Server is already active for display 0
If this server is no longer running, remove /tmp/.X0-lock
and start again.
(EE)
[services.d] xvfb: starting...
(EE)
Fatal server error: 
```

**Comment by jlesage** [comment] 2017-07-29 13:29
Is your container still in this state?  If yes, could your provide the output of these docker commands:

Full container logs:
`docker logs <container ID>`

Process list:
`docker exec <container ID> ps - A`

**Comment by DaLeberkasPepi** [comment] 2017-07-29 15:08
Full Container logs:
https://pastebin.com/cEYTR63n

Process list:
https://pastebin.com/AnZfNpDu

**Comment by jlesage** [comment] 2017-07-29 15:31
Thank you very much!  I would need additional info:

Container version:
`docker inspect <container id> | grep version`

Execute this command.  This should output a PID (numeric value).
`docker exec <container id> cat /tmp/.X0-lock`

Then, with this value, run:
`docker exec <container id> cat /proc/<PID>/cmdline`

**Comment by DaLeberkasPepi** [comment] 2017-07-29 16:56
```
Linux 4.12.3-unRAID.
root@HomeServer:~# docker inspect 5ae6f3cb730d946640a3baa62f87e7752eefe8cbb269b82c6de93ff796cb022f | grep version
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.version": "1.1.3"
root@HomeServer:~# docker exec 5ae6f3cb730d946640a3baa62f87e7752eefe8cbb269b82c6de93ff796cb022f cat /tmp/.X0-lock
       302
root@HomeServer:~# docker exec 5ae6f3cb730d946640a3baa62f87e7752eefe8cbb269b82c6de93ff796cb022f cat /proc/302/cmdline
sh./runroot@HomeServer:~#

```

**Comment by DaLeberkasPepi** [comment] 2017-07-29 17:09
sry i forgot to say that i run Unraid 6.4.0-rc7a

**Comment by jlesage** [comment] 2017-07-30 02:15
Can you provide the full content of the inspect command?
`docker inspect <container id>`

In unRAID, are you configured to automatically update your docker containers?

**Comment by DaLeberkasPepi** [comment] 2017-07-30 07:48
Yes this container is setup to autoupdate in unRAID.

docker inspect:
````
Linux 4.12.3-unRAID.
root@HomeServer:~# docker inspect 5ae6f3cb730d946640a3baa62f87e7752eefe8cbb269b8                                                                                       2c6de93ff796cb022f
[
    {
        "Id": "5ae6f3cb730d946640a3baa62f87e7752eefe8cbb269b82c6de93ff796cb022f"                                                                                       ,
        "Created": "2017-07-27T22:02:28.580935715Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 24373,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-07-29T13:18:03.933802529Z",
            "FinishedAt": "2017-07-29T13:18:03.391751369Z"
        },
        "Image": "sha256:06564e5c87d1f1f4f0fdb7b2ae073295b1edc1a4dd03495b1f1c022                                                                                       5762d39a9",
        "ResolvConfPath": "/var/lib/docker/containers/5ae6f3cb730d946640a3baa62f                                                                                       87e7752eefe8cbb269b82c6de93ff796cb022f/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/5ae6f3cb730d946640a3baa62f87                                                                                       e7752eefe8cbb269b82c6de93ff796cb022f/hostname",
        "HostsPath": "/var/lib/docker/containers/5ae6f3cb730d946640a3baa62f87e77                                                                                       52eefe8cbb269b82c6de93ff796cb022f/hosts",
        "LogPath": "/var/lib/docker/containers/5ae6f3cb730d946640a3baa62f87e7752                                                                                       eefe8cbb269b82c6de93ff796cb022f/5ae6f3cb730d946640a3baa62f87e7752eefe8cbb269b82c                                                                                       6de93ff796cb022f-json.log",
        "Name": "/JDownloader2",
        "RestartCount": 0,
        "Driver": "btrfs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/mnt/user/Adult/:/Adult:rw",
                "/mnt/user/appdata/JDownloader2:/config:rw",
                "/mnt/user/Downloads/:/output:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7807"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7907"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "2,3,10,11",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/user/Adult",
                "Destination": "/Adult",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/mnt/user/appdata/JDownloader2",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/mnt/user/Downloads",
                "Destination": "/output",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "89a243bc006ad27f8b334cfb0520b327669c4020dcc7c9329c70289                                                                                       821410238",
                "Source": "/var/lib/docker/volumes/89a243bc006ad27f8b334cfb0520b                                                                                       327669c4020dcc7c9329c70289821410238/_data",
                "Destination": "/storage",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "5ae6f3cb730d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "TZ=Europe/Berlin",
                "HOST_OS=unRAID",
                "KEEP_GUIAPP_RUNNING=1",
                "USER_ID=99",
                "GROUP_ID=100",
                "UMASK=000",
                "DISPLAY_WIDTH=1920",
                "DISPLAY_HEIGHT=1080",
                "APP_NICENESS=",
                "X11VNC_EXTRA_OPTS=",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b                                                                                       in",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "APP_NAME=JDownloader 2",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "DISPLAY=:0",
                "S6_KILL_FINISH_MAXTIME=20000"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "jlesage/jdownloader-2",
            "Volumes": {
                "/config": {},
                "/output": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.description": "Docker container for JDownloade                                                                                       r 2",
                "org.label-schema.name": "jdownloader-2",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-j                                                                                       downloader-2",
                "org.label-schema.version": "1.1.3"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "0a42dd6f17201e06f9a458a5651752596f2d983ef2c48068332cee                                                                                       3b1089188c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7807"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7907"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/0a42dd6f1720",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "642e32f673cd1d3fb2890f466d6799d5da20114d180ed421fad90                                                                                       ccb6070b5f0",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.7",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:07",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "cb6a8105312fda7ee10126a18e101d83cc971dc28b15c0                                                                                       0474a341ada1391ea2",
                    "EndpointID": "642e32f673cd1d3fb2890f466d6799d5da20114d180ed                                                                                       421fad90ccb6070b5f0",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.7",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:07"
                }
            }
        }
    }
]

**Comment by DaLeberkasPepi** [comment] 2017-07-30 08:10
After a reinstall of the doctor it works normal. Maybe something in the autoupdate went wrong 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jlesage** [comment] 2017-07-31 00:34
Yeah probably that a restart of the container would have fixed the issue.

As I can't reproduce myself, I'm trying to understand how it could occur.  With the information you provided I should be able to push a fix.

**Comment by DaLeberkasPepi** [comment] 2017-07-31 02:57
And it happened again. The docker is again in the same state as described in my first post.

**Comment by jlesage** [comment] 2017-07-31 09:22
No action performed on your side?
Can you provide the full log again?

**Comment by DaLeberkasPepi** [comment] 2017-07-31 10:43
Not directly at least. The ca backup Plugin was running over night so the Docker had to be stopped by the Plugin. As side from that I was only using jdownloader2 over webui to download stuff but nothing else. 

I'll post the logs when I get home from work. 
Only those:
Full container logs:
docker logs <container ID>

Process list:
docker exec <container ID> ps - A

Or also the rest?

**Comment by jlesage** [comment] 2017-07-31 12:19
Only the command `docker logs <container ID>` would be enough.  But if it's too long after the start we miss the very first messages.

**Comment by jlesage** [comment] 2017-07-31 12:20
The fact that the container has been stopped is a good information: this confirms my theory :)

**Comment by DaLeberkasPepi** [comment] 2017-07-31 13:24
i can restart the container so the log starts fresh. The error persists until i recreate the docker from the template. And just for reference when i recreated the docker and it the container was working i immediatly tried a docker restart but not stop and start. 
Should i recreate the docker after i generated the docker logs and try to stop and start it to reproduce the error?

**Comment by jlesage** [comment] 2017-07-31 13:35
If you fall in the same situation after restarting the container, then this would be enough.
But I'm now pretty sure of what is the issue.  Currently working on a fix.

**Comment by DaLeberkasPepi** [comment] 2017-07-31 13:48
i did test that already yesterday. if i just restart the container i get the same log output as mentioned in the third post. https://pastebin.com/cEYTR63n.
The only thing that "fixes" that is a recreate of the docker file but i can't 100% tell what produces that problems in the first place since the docker worked fine for a few hours after i recreated the docker file.

**Comment by jlesage** [comment] 2017-07-31 14:01
The trigger for the issue is a container restart (or a stop followed by a start).

The X server is failing to start because `/tmp/.X0-lock` exists and contains the PID of a running process.

Normally, this file is removed when the X server is stopped.  But when the container is stopped, the X server is not stopped gracefully, preventing the lock file to be removed.  Then, when the container is starting again, the previous lock file still exists.  If by chance the stored PID matches the one of a running process, the X server will fail to start.

The first time the container starts (after recreating it) the lock file doesn't exist yet.  Thus, no problem until the container is restarted.

**Comment by DaLeberkasPepi** [comment] 2017-07-31 14:47
the log after a fresh reboot of the docker:
````
[cont-prefinish.d] 10-kill-app: exited 0.
[cont-prefinish.d] 20-kill-openbox: executing...
[cont-prefinish.d] 20-kill-openbox: exited 0.
[cont-prefinish.d] 20-kill-x11vnc: executing...
[cont-prefinish.d] 20-kill-x11vnc: exited 0.
[cont-prefinish.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
s6-svstat: fatal: unable to read status for /var/run/s6/services/xvfb: s6-supervise not running
s6-svstat: fatal: unable to read status for /var/run/s6/services/xvfb: s6-supervise not running
[services.d] x11vnc: waiting for xvfb to be ready...
[services.d] openbox: waiting for xvfb to be ready...
s6-svstat: fatal: unable to read status for /var/run/s6/services/openbox: s6-supervise not running
[services.d] app: waiting for openbox to be ready...
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 10-startapp-attrs.sh: executing...
[cont-init.d] 10-startapp-attrs.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] jdownloader2.sh: executing...
[cont-init.d] jdownloader2.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[services.d] app: waiting for openbox to be ready...
[services.d] xvfb: starting...
[services.d] openbox: waiting for xvfb to be ready...
[services.d] x11vnc: waiting for xvfb to be ready...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] openbox: waiting for xvfb to be ready...
[services.d] x11vnc: waiting for xvfb to be ready...
[services.d] app: waiting for openbox to be ready...
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] openbox: waiting for xvfb to be ready...
[services.d] x11vnc: waiting for xvfb to be ready...
[services.d] app: waiting for openbox to be ready...
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] openbox: waiting for xvfb to be ready...
[services.d] x11vnc: waiting for xvfb to be ready...
[services.d] app: waiting for openbox to be ready...
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] openbox: waiting for xvfb to be ready...
[services.d] x11vnc: waiting for xvfb to be ready...
[services.d] app: waiting for openbox to be ready...
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] openbox: waiting for xvfb to be ready...
[services.d] x11vnc: waiting for xvfb to be ready...
[services.d] app: waiting for openbox to be ready...
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] openbox: waiting for xvfb to be ready...
[services.d] x11vnc: waiting for xvfb to be ready...
[services.d] app: waiting for openbox to be ready...
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] xvfb: starting...
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
[services.d] openbox: waiting for xvfb to be ready...
[services.d] x11vnc: waiting for xvfb to be ready...
[services.d] app: waiting for openbox to be ready...

**Comment by jlesage** [comment] 2017-07-31 18:09
Try the latest image, problem should be fixed.
Re-open the issue if it's not the case.
Thanks for your help on this!

**Closed by jlesage** 2017-07-31 18:09 UTC

**Comment by DaLeberkasPepi** [comment] 2017-07-31 18:14
I have to thank YOU! Really appreciate how fast you could fix this problem in your free time

**Comment by DaLeberkasPepi** [comment] 2017-07-31 19:19
How can i buy you a beer? ;)

**Comment by jlesage** [comment] 2017-08-01 00:49
That's a good question.  Will check that and come back to you ;)
