### ISSUE TITLE
Options to enable support for Chinese character?

### ISSUE THREAD

**Issue by jacobhogary** [jlesage/docker-jdownloader-2#10] opened 2018-01-17 16:44 UTC
Hi,
I am having a problem of chinese character is not display correct. It just showing like boxes for the character. Is there options to enable chinese character to the system of the docker?
Thanks

**Comment by jlesage** [comment] 2018-01-17 17:07
Did you try to change the font ? In Settings -> Advanced Settings, search for "Font name".  Set the value to  "Dialog".
See https://board.jdownloader.org/showthread.php?t=65408

**Comment by jacobhogary** [comment] 2018-01-17 17:16
Yes i have just tried that. It remain the same. Maybe it is because of the base system dont have the font to support the character?

**Comment by jlesage** [comment] 2018-01-17 17:27
Maybe... could you provide a way for me to reproduce the issue?

**Comment by jacobhogary** [comment] 2018-01-17 17:37
[https://www.youtube.com/watch?v=xpT7av-kiXg](url)
Here is the youtube link contain chinese character. When i add it to the linkgrabber, the name just show "boxes" which should be the chinese character.

Or you can try change the language interface of jdownloader to Chinese(Taiwan). It will also just showing "boxes"

**Comment by jacobhogary** [comment] 2018-01-17 18:22
After doing a little bit of research. i have fixed it by install fontconfig and install the Chinese font from [Here](https://sourceforge.net/projects/wqy/files/wqy-zenhei/0.8.38%20%28Pangu%29/wqy-zenhei-0.8.38-1.tar.gz/download)

**Comment by jlesage** [comment] 2018-01-17 18:29
Yeah I also found this font for Alpine.  It can be installed with `add-pkg wqy-zenhei --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing`.
However, none of the available font (`WenQuanYi Zen Hei Mono`, `WenQuanYi Zen Hei Sharp`, `WenQuanYi Zen Hei`) seems to look good.
Which one did you enabled in JDownloader?

**Comment by jacobhogary** [comment] 2018-01-17 18:35
Hmmm i think it is WenQuanYi Zen Hei. I just install the font file manually by downloading above zip file. Then extract wqy-zenhei.ttc into /usr/share/fonts/wqy-zenhey and then run fc-cache. Finally just restart the docker.

**Comment by jlesage** [comment] 2018-01-21 02:09
Installing the font with `add-pkg wqy-zenhei --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing` and keeping the `Font Name` in JDownloader to `default` seems to be the right solution.

I will find a way to provide an option to automatically install this when wanted.

**Comment by jlesage** [comment] 2018-01-22 19:49
With the latest image, to automatically install the `WenQuanYi Zen Hei` font, you just need to set the environment variable  `ENABLE_CJK_FONT` to `1`.

When this variable is set, the existence of the font is verified during startup.  If missing, it will be installed automatically.

**Closed by jlesage** 2018-01-22 19:49 UTC

**Comment by huiguo2008** [comment] 2021-10-05 16:25
> With the latest image, to automatically install the `WenQuanYi Zen Hei` font, you just need to set the environment variable `ENABLE_CJK_FONT` to `1`.
> 
> When this variable is set, the existence of the font is verified during startup. If missing, it will be installed automatically.

Hi, where I can find the setting? how can i do it? could you please give more info about it? thanx

**Comment by jlesage** [comment] 2021-10-18 13:17
This is a container environment variable you need to add.  If you use the command line, you need to add the `-p ENABLE_CJK_FONT=1` parameter to your `docker run` command.
