### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by erdnussflips** [jlesage/docker-jdownloader-2#12] opened 2018-04-29 20:06 UTC
When I try to start the container in a clean environment, I always getting the error: 
> Could not set /config/JDownloader.jar executable to TRUE

My start command:
`docker run -d --name=jdownloader-2 -p 5800:5800 jlesage/jdownloader-2`

**Comment by jlesage** [comment] 2018-04-30 00:00
On which system are you running the container?  Can you provide the whole docker log?

**Comment by ErdnussFlipS** [comment] 2018-05-01 13:26
System information:
> $ docker --version
Docker version 18.03.1-ce, build 9ee9f40

> $ uname -a
Linux ****** 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

> $ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch

Update exception:
> org.appwork.updatesys.client.InstallException: Could not set /config/JDownloader.jar executable toTRUE
	at org.appwork.updatesys.client.UpdateClient.applyClientOptions(UpdateClient.java:461)
	at org.appwork.updatesys.client.UpdateClient.runPackageInstallation(UpdateClient.java:3152)
	at org.jdownloader.update.JDUpdateClient.runPackageInstallation(JDUpdateClient.java:183)
	at org.jdownloader.update.UpdateManager.installPendingAWFFiles(UpdateManager.java:686)
	at org.jdownloader.update.DefaultCallbackHandler.onResults(DefaultCallbackHandler.java:396)
	at org.jdownloader.update.UpdateManager.runUpdateLoop(UpdateManager.java:1055)
	at org.jdownloader.update.UpdateManager$4.run(UpdateManager.java:386)
	at java.lang.Thread.run(Thread.java:748)

Container log:
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 00-app-niceness.sh: executing... ,
[cont-init.d] 00-app-niceness.sh: exited 0.,
[cont-init.d] 00-app-script.sh: executing... ,
[cont-init.d] 00-app-script.sh: exited 0.,
[cont-init.d] 00-app-user-map.sh: executing... ,
[cont-init.d] 00-app-user-map.sh: exited 0.,
[cont-init.d] 00-clean-logmonitor-states.sh: executing... ,
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.,
[cont-init.d] 00-clean-tmp-dir.sh: executing... ,
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.,
[cont-init.d] 00-set-app-deps.sh: executing... ,
[cont-init.d] 00-set-app-deps.sh: exited 0.,
[cont-init.d] 00-set-home.sh: executing... ,
[cont-init.d] 00-set-home.sh: exited 0.,
[cont-init.d] 00-take-config-ownership.sh: executing... ,
[cont-init.d] 00-take-config-ownership.sh: exited 0.,
[cont-init.d] 10-certs.sh: executing... ,
[cont-init.d] 10-certs.sh: exited 0.,
[cont-init.d] 10-cjk-font.sh: executing... ,
[cont-init.d] 10-cjk-font.sh: exited 0.,
[cont-init.d] 10-nginx.sh: executing... ,
[cont-init.d] 10-nginx.sh: exited 0.,
[cont-init.d] 10-vnc-password.sh: executing... ,
[cont-init.d] 10-vnc-password.sh: exited 0.,
[cont-init.d] 10-web-index.sh: executing... ,
[cont-init.d] 10-web-index.sh: exited 0.,
[cont-init.d] jdownloader2.sh: executing... ,
[cont-init.d] jdownloader2.sh: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] starting s6-fdholderd...,
[services.d] starting nginx...,
[services.d] starting certsmonitor...,
[nginx] starting...,
[services.d] starting xvfb...,
[certsmonitor] disabling service: secure connection not enabled.,
[xvfb] starting...,
[services.d] starting statusmonitor...,
[services.d] starting x11vnc...,
[statusmonitor] no file to monitor: disabling service...,
[services.d] starting openbox...,
[x11vnc] starting...,
01/05/2018 13:18:34 passing arg to libvncserver: -rfbport,
01/05/2018 13:18:34 passing arg to libvncserver: 5900,
01/05/2018 13:18:34 passing arg to libvncserver: -rfbportv6,
01/05/2018 13:18:34 passing arg to libvncserver: -1,
01/05/2018 13:18:34 passing arg to libvncserver: -httpportv6,
01/05/2018 13:18:34 passing arg to libvncserver: -1,
01/05/2018 13:18:34 passing arg to libvncserver: -desktop,
01/05/2018 13:18:34 passing arg to libvncserver: JDownloader 2,
01/05/2018 13:18:34 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 763,
[openbox] starting...,
01/05/2018 13:18:34 Using X display :0,
01/05/2018 13:18:34 rootwin: 0x43 reswin: 0x200001 dpy: 0xfaa5ca40,
01/05/2018 13:18:34 ,
01/05/2018 13:18:34 ------------------ USEFUL INFORMATION ------------------,
01/05/2018 13:18:34 X DAMAGE available on display, using it for polling hints.,
01/05/2018 13:18:34   To disable this behavior use: '-noxdamage',
01/05/2018 13:18:34 ,
01/05/2018 13:18:34   Most compositing window managers like 'compiz' or 'beryl',
01/05/2018 13:18:34   cause X DAMAGE to fail, and so you may not see any screen,
01/05/2018 13:18:34   updates via VNC.  Either disable 'compiz' (recommended) or,
01/05/2018 13:18:34   supply the x11vnc '-noxdamage' command line option.,
01/05/2018 13:18:34 X COMPOSITE available on display, using it for window polling.,
01/05/2018 13:18:34   To disable this behavior use: '-noxcomposite',
01/05/2018 13:18:34 ,
01/05/2018 13:18:34 Wireframing: -wireframe mode is in effect for window moves.,
01/05/2018 13:18:34   If this yields undesired behavior (poor response, painting,
01/05/2018 13:18:34   errors, etc) it may be disabled:,
01/05/2018 13:18:34    - use '-nowf' to disable wireframing completely.,
01/05/2018 13:18:34    - use '-nowcr' to disable the Copy Rectangle after the,
01/05/2018 13:18:34      moved window is released in the new position.,
01/05/2018 13:18:34   Also see the -help entry for tuning parameters.,
01/05/2018 13:18:34   You can press 3 Alt_L's (Left "Alt" key) in a row to ,
01/05/2018 13:18:34   repaint the screen, also see the -fixscreen option for,
01/05/2018 13:18:34   periodic repaints.,
01/05/2018 13:18:34 GrabServer control via XTEST.,
01/05/2018 13:18:34 ,
01/05/2018 13:18:34 Scroll Detection: -scrollcopyrect mode is in effect to,
01/05/2018 13:18:34   use RECORD extension to try to detect scrolling windows,
01/05/2018 13:18:34   (induced by either user keystroke or mouse input).,
01/05/2018 13:18:34   If this yields undesired behavior (poor response, painting,
01/05/2018 13:18:34   errors, etc) it may be disabled via: '-noscr',
01/05/2018 13:18:34   Also see the -help entry for tuning parameters.,
01/05/2018 13:18:34   You can press 3 Alt_L's (Left "Alt" key) in a row to ,
01/05/2018 13:18:34   repaint the screen, also see the -fixscreen option for,
01/05/2018 13:18:34   periodic repaints.,
01/05/2018 13:18:34 ,
01/05/2018 13:18:34 XKEYBOARD: number of keysyms per keycode 7 is greater,
01/05/2018 13:18:34   than 4 and 51 keysyms are mapped above 4.,
01/05/2018 13:18:34   Automatically switching to -xkb mode.,
01/05/2018 13:18:34   If this makes the key mapping worse you can,
01/05/2018 13:18:34   disable it with the "-noxkb" option.,
01/05/2018 13:18:34   Also, remember "-remap DEAD" for accenting characters.,
01/05/2018 13:18:34 ,
01/05/2018 13:18:34 X FBPM extension not supported.,
01/05/2018 13:18:34 X display is not capable of DPMS.,
01/05/2018 13:18:34 --------------------------------------------------------,
01/05/2018 13:18:34 ,
01/05/2018 13:18:34 Default visual ID: 0x21,
01/05/2018 13:18:34 Read initial data from X display into framebuffer.,
01/05/2018 13:18:34 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120,
01/05/2018 13:18:34 ,
01/05/2018 13:18:34 X display :0 is 32bpp depth=24 true color,
01/05/2018 13:18:34 ,
01/05/2018 13:18:34 Listening for VNC connections on TCP port 5900,
01/05/2018 13:18:34 ,
01/05/2018 13:18:34 Xinerama is present and active (e.g. multi-head).,
01/05/2018 13:18:34 Xinerama: number of sub-screens: 1,
01/05/2018 13:18:34 Xinerama: no blackouts needed (only one sub-screen),
01/05/2018 13:18:34 ,
01/05/2018 13:18:34 fb read rate: 2257 MB/sec,
01/05/2018 13:18:34 fast read: reset -wait  ms to: 10,
01/05/2018 13:18:34 fast read: reset -defer ms to: 10,
01/05/2018 13:18:34 The X server says there are 10 mouse buttons.,
01/05/2018 13:18:34 screen setup finished.,
01/05/2018 13:18:34 ,
,
The VNC desktop is:      5d1f567336ce:0,,
0,
,
******************************************************************************,
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?,
,
The scheme stores pixel data offscreen on the VNC viewer side for faster,
retrieval.  It should work with any VNC viewer.  Try it by running:,
,
    x11vnc -ncache 10 ...,
,
One can also add -ncache_cr for smooth 'copyrect' window motion.,
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching,
,
Openbox-Message: Openbox was compiled without image loading support. Icons in menus will not be loaded.,
[services.d] starting logmonitor...,
[services.d] starting app...,
[logmonitor] no file to monitor: disabling service...,
[app] starting JDownloader 2...,
[services.d] done.,
[jdsupervisor] JDownloader2 not started yet.  Proceeding...,
01/05/2018 13:18:38 Got connection from client 127.0.0.1,
01/05/2018 13:18:38   other clients:,
01/05/2018 13:18:38 Got 'ws' WebSockets handshake,
01/05/2018 13:18:38 Got protocol: binary,
01/05/2018 13:18:38   - webSocketsHandshake: using binary/raw encoding,
01/05/2018 13:18:38   - WebSockets client version hybi-13,
01/05/2018 13:18:38 Disabled X server key autorepeat.,
01/05/2018 13:18:38   to force back on run: 'xset r on' (3 times),
01/05/2018 13:18:38 incr accepted_client=1 for 127.0.0.1:57768  sock=10,
01/05/2018 13:18:39 Client Protocol Version 3.8,
01/05/2018 13:18:39 Protocol version sent 3.8, using 3.8,
01/05/2018 13:18:39 rfbProcessClientSecurityType: executing handler for type 1,
01/05/2018 13:18:39 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8,
01/05/2018 13:18:39 copy_tiles: allocating first_line at size 41,
01/05/2018 13:18:39 Pixel format for client 127.0.0.1:,
01/05/2018 13:18:39   32 bpp, depth 24, little endian,
01/05/2018 13:18:39   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0,
01/05/2018 13:18:39 no translation needed,
01/05/2018 13:18:39 Enabling NewFBSize protocol extension for client 127.0.0.1,
01/05/2018 13:18:39 Enabling full-color cursor updates for client 127.0.0.1,
01/05/2018 13:18:39 Using image quality level 6 for client 127.0.0.1,
01/05/2018 13:18:39 Using JPEG subsampling 0, Q79 for client 127.0.0.1,
01/05/2018 13:18:39 Using compression level 9 for client 127.0.0.1,
01/05/2018 13:18:39 Enabling LastRect protocol extension for client 127.0.0.1,
01/05/2018 13:18:39 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC),
01/05/2018 13:18:39 Using tight encoding for client 127.0.0.1,
01/05/2018 13:18:39 client_set_net: 127.0.0.1  0.0001,
01/05/2018 13:18:39 created   xdamage object: 0x20002c,
01/05/2018 13:18:48 created selwin: 0x20002d,
01/05/2018 13:18:48 called initialize_xfixes(),
01/05/2018 13:19:01 client 1 network rate 360.9 KB/sec (26726.9 eff KB/sec),
01/05/2018 13:19:01 client 1 latency:  2.4 ms,
01/05/2018 13:19:01 dt1: 0.0196, dt2: 0.0146 dt3: 0.0024 bytes: 11933,
01/05/2018 13:19:01 link_rate: LR_LAN - 2 ms, 360 KB/s,

**Comment by jlesage** [comment] 2018-05-01 15:30
Could you provide the output of:
`docker exec jdownloader-2 ls -l /`
`docker exec jdownloader-2 ls -l /config`

Also, I'm assuming you are running the latest image version?  Did you try to map the `/config` folder?

**Comment by ErdnussFlipS** [comment] 2018-05-01 18:31
Yes, it tried the latest image:
> docker volume create jdownloader2-test_config
docker run -d --name=jdownloader2-test -p 5800:5800 -v jdownloader2-test_config:/config jlesage/jdownloader-2:v1.4.3

Here the requested output (i attached both, persisted and temporary volume mount):
[jdownloader2.withoutMount.config.txt](https://github.com/jlesage/docker-jdownloader-2/files/1964785/jdownloader2.withoutMount.config.txt)
[jdownloader2.withoutMount.root.txt](https://github.com/jlesage/docker-jdownloader-2/files/1964786/jdownloader2.withoutMount.root.txt)
[jdownloader2.withMount.root.txt](https://github.com/jlesage/docker-jdownloader-2/files/1964787/jdownloader2.withMount.root.txt)
[jdownloader2.withMount.config.txt](https://github.com/jlesage/docker-jdownloader-2/files/1964788/jdownloader2.withMount.config.txt)

**Comment by jlesage** [comment] 2018-05-01 19:09
And what about:
`docker exec jdownloader-2 ps -A`
`docker inspect jdownloader-2`

**Comment by jlesage** [comment] 2018-07-09 10:35
Do you get the same error if you don't map the `/config` folder?

**Comment by computeus** [comment] 2018-07-09 21:37
It works if I do not map config folder.

**Comment by jlesage** [comment] 2018-07-10 09:44
So there is something wrong with the mapping of `/config`.  Could you provide the output of (when `/config` is mapped):
  - `docker exec jdownloader-2 ls -l /`
  - `docker exec jdownloader-2 ls -l /config`

**Comment by computeus** [comment] 2018-07-11 23:41
`docker exec jdownloader-2 ls -l /`

> total 112
drwxr-xr-x    1 root     root          4096 Mar  3 00:20 bin
drwxr-sr-x    8 app      app           4096 Jul 12 02:37 config
drwxr-xr-x    1 root     root          4096 Mar  3 00:18 defaults
drwxr-xr-x    5 root     root           340 Jul 12 02:37 dev
drwxr-xr-x    1 root     root          4096 Jul 12 02:37 etc
drwxr-xr-x    1 root     root          4096 Mar  2 13:49 home
-rwxr-xr-x    1 root     root           389 Dec 19  2017 init
drwxr-xr-x    1 root     root          4096 Mar  3 00:19 lib
drwxr-xr-x    2 root     root          4096 Mar  2 13:48 lib64
drwxr-xr-x    2 root     root          4096 Nov  1  2017 libexec
drwxr-xr-x    5 root     root          4096 Jan  9  2018 media
drwxr-xr-x    2 root     root          4096 Jan  9  2018 mnt
drwxr-xr-x    1 root     root          4096 Mar  3 00:19 opt
drwxrwsrwx   15 app      app           4096 Jul 12 02:37 output
dr-xr-xr-x  266 root     root             0 Jul 12 02:37 proc
drwx------    2 root     root          4096 Jan  9  2018 root
drwxr-xr-x    1 root     root          4096 Jul 12 02:37 run
drwxr-xr-x    1 root     root          4096 Mar  2 13:49 sbin
drwxr-xr-x    2 root     root          4096 Jan  9  2018 srv
-rwxr-xr-x    1 root     root          1413 Mar  3 00:18 startapp.sh
drwxrwsrwx   15 app      app           4096 Jul 12 02:37 storage
dr-xr-xr-x   13 root     root             0 Jul 12 02:37 sys
drwxrwxrwt    1 root     root          4096 Jul 12 02:37 tmp
drwxr-xr-x    1 root     root          4096 Mar  3 00:19 usr
drwxr-xr-x    1 root     root          4096 Mar  3 00:19 var


`docker exec jdownloader-2 ls -l /config`

> total 3328
-rw-rw-rw-    1 app      app              0 Jul 12 02:37 JD2.lock
-rw-rw-rw-    1 app      app              4 Jul 12 02:37 JD2.port
-rw-r--r--    1 app      app        3329436 Jul 12 02:37 JDownloader.jar
-rw-rw-rw-    1 app      app              4 Jul 12 02:37 JDownloader.pid
drwxr-xr-x    2 app      app           4096 Jul 12 02:37 cfg
-rw-r--r--    1 app      app           1115 Jul 12 02:37 default_site.conf
-rw-r--r--    1 app      app            424 Jul 12 02:37 dhparam.pem
-rw-r--r--    1 app      app            696 Jul 12 02:37 group
drwxrwsrwx    3 app      app           4096 Jul 12 02:37 log
drwxrwsrwx    3 app      app           4096 Jul 12 02:37 logs
-rw-r--r--    1 app      app           1265 Jul 12 02:37 passwd
-rw-r-----    1 app      app            440 Jul 12 02:37 shadow
drwxrwsrwx    3 app      app           4096 Jul 12 02:37 tmp
drwxrwsrwx    3 app      app           4096 Jul 12 02:37 update
drwxrwsrwx    3 app      app           4096 Jul 12 02:37 xdg

**Comment by jlesage** [comment] 2018-07-12 10:20
And if you map `/config` to a different, empty folder?  If this is working, then try to run the following command (with the container having `/config` mapped to the folder producing the error):

`docker exec jd2 chmod 766 /config/JDownloader.jar`

**Comment by computeus** [comment] 2018-07-12 17:30
The last output I sent is from a new empty folder.

**Comment by jlesage** [comment] 2018-07-13 10:40
And what's the output of `df -h` (on the host)?

**Comment by spaceman** [comment] 2018-08-29 23:14
Same problem here when i map the volume config. Is there any solution?

**Comment by jlesage** [comment] 2018-08-30 01:55
It’s probably related to the underlying file system.  On which system are you running the container?

**Comment by spaceman** [comment] 2018-08-31 17:38
Sorry for my late response. The config data are on a ext4 share.

My workaround is to start the container the first time without mapping the volume. Then i stop the container and move the unnamed volume from /var/lib/docker/volumes to /sharedfolders/AppData/jdownloader. After that the volume starts without any errors.

**Comment by spaceman** [comment] 2018-09-07 20:30
Unfortunately right now i have a different problem. As soon as the captcha dialog appears jdownloader 2 crash. In the log i found this: 

Inconsistency detected by ld.so: dl-lookup.c: 128: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

Here is the output of docker exec jdownloader2 df -h:

Filesystem                Size      Used Available Use% Mounted on
overlay                  25.5G     16.7G      7.4G  69% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     1.9G         0      1.9G   0% /sys/fs/cgroup
/dev/sda1                25.5G     16.7G      7.4G  69% /config
/dev/md126               19.5G     17.0G      2.5G  87% /output
/dev/sda1                25.5G     16.7G      7.4G  69% /storage
/dev/sda1                25.5G     16.7G      7.4G  69% /etc/localtime
/dev/sda1                25.5G     16.7G      7.4G  69% /etc/resolv.conf
/dev/sda1                25.5G     16.7G      7.4G  69% /etc/hostname
/dev/sda1                25.5G     16.7G      7.4G  69% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     1.9G         0      1.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     1.9G         0      1.9G   0% /sys/firmware

**Comment by jlesage** [comment] 2018-09-08 17:15
> As soon as the captcha dialog appears jdownloader 2 crash.

Do you mean that you perform a download that requires resolving captcha?    Which captcha resolver are you using?

**Comment by jlesage** [comment] 2018-09-08 20:30
You should probably disable "Dialog (Window) in Browser", since there is no browser available the container.  Can you try to active others one at time to see which one could cause the crash?

**Comment by jlesage** [comment] 2018-09-10 10:16
The `noexec` mount option does not allow the execution of executable binaries in the mounted file system.  So yes it could be a problem.  Can you try without this option to see if it fixes the issue?

**Comment by pokrzys** [comment] 2018-09-10 15:26
Just did and it's working as expected at partition mounted without `noexec` flag :-) 
The problem is that openmediavault mount every partition with `noexec` by default and to change this behaviour you need to alter fstab parameter in environmental variables.
It can be done by editing `/etc/default/openmediavault` file and adding at the end:
`OMV_FSTAB_MNTOPS_EXT4=defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0")` - in case using ext4 of course.
OMV needs to be restarted and already mounted partitions needs to be remounted after adding this line.
Maybe someone can make use of it.
Thanks for your answer @jlesage

**Comment by jlesage** [comment] 2018-09-22 01:08
With the latest image (`v1.5.0`), JDownloader should work without issue from a filesystem without execution permission.
Thanks to the developer of JDownloader who quickly pushed some fixes to make this work!

**Closed by jlesage** 2018-09-22 01:08 UTC

**Comment by funkythings** [comment] 2020-03-25 08:50
I'm getting the same error in the browser, which is strange, because it just worked yesterday.

System:
Ubuntu 18.04

Docker command:
```
sudo docker run --rm --name=jdownloader-2 -p 5800:5800 -v /media/julian/moviesIII/jdownloader/config:/config:rw -v /media/julian/moviesIII/jdownloader:/output:rw jlesage/jdownloader-2
```

Ouput of container:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing... 
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing... 
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing... 
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing... 
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing... 
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing... 
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing... 
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing... 
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing... 
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing... 
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing... 
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing... 
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing... 
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] jdownloader2.sh: executing... 
[cont-init.d] jdownloader2.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting xvfb...
[xvfb] starting...
[services.d] starting certsmonitor...
[services.d] starting nginx...
[certsmonitor] disabling service: secure connection not enabled.
[nginx] starting...
[services.d] starting x11vnc...
[services.d] starting statusmonitor...
[x11vnc] starting...
[statusmonitor] no file to monitor: disabling service...
25/03/2020 08:47:54 passing arg to libvncserver: -rfbport
25/03/2020 08:47:54 passing arg to libvncserver: 5900
25/03/2020 08:47:54 passing arg to libvncserver: -rfbportv6
25/03/2020 08:47:54 passing arg to libvncserver: -1
25/03/2020 08:47:54 passing arg to libvncserver: -httpportv6
25/03/2020 08:47:54 passing arg to libvncserver: -1
25/03/2020 08:47:54 passing arg to libvncserver: -desktop
25/03/2020 08:47:54 passing arg to libvncserver: JDownloader 2
25/03/2020 08:47:54 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 9712
25/03/2020 08:47:54 Using X display :0
25/03/2020 08:47:54 rootwin: 0x43 reswin: 0x200001 dpy: 0xd3c9c9e0
25/03/2020 08:47:54 
25/03/2020 08:47:54 ------------------ USEFUL INFORMATION ------------------
25/03/2020 08:47:54 X DAMAGE available on display, using it for polling hints.
25/03/2020 08:47:54   To disable this behavior use: '-noxdamage'
25/03/2020 08:47:54 
25/03/2020 08:47:54   Most compositing window managers like 'compiz' or 'beryl'
25/03/2020 08:47:54   cause X DAMAGE to fail, and so you may not see any screen
25/03/2020 08:47:54   updates via VNC.  Either disable 'compiz' (recommended) or
25/03/2020 08:47:54   supply the x11vnc '-noxdamage' command line option.
25/03/2020 08:47:54 X COMPOSITE available on display, using it for window polling.
25/03/2020 08:47:54   To disable this behavior use: '-noxcomposite'
25/03/2020 08:47:54 
25/03/2020 08:47:54 Wireframing: -wireframe mode is in effect for window moves.
25/03/2020 08:47:54   If this yields undesired behavior (poor response, painting
25/03/2020 08:47:54   errors, etc) it may be disabled:
25/03/2020 08:47:54    - use '-nowf' to disable wireframing completely.
25/03/2020 08:47:54    - use '-nowcr' to disable the Copy Rectangle after the
25/03/2020 08:47:54      moved window is released in the new position.
25/03/2020 08:47:54   Also see the -help entry for tuning parameters.
25/03/2020 08:47:54   You can press 3 Alt_L's (Left "Alt" key) in a row to 
25/03/2020 08:47:54   repaint the screen, also see the -fixscreen option for
25/03/2020 08:47:54   periodic repaints.
25/03/2020 08:47:54 GrabServer control via XTEST.
25/03/2020 08:47:54 
25/03/2020 08:47:54 Scroll Detection: -scrollcopyrect mode is in effect to
25/03/2020 08:47:54   use RECORD extension to try to detect scrolling windows
25/03/2020 08:47:54   (induced by either user keystroke or mouse input).
25/03/2020 08:47:54   If this yields undesired behavior (poor response, painting
25/03/2020 08:47:54   errors, etc) it may be disabled via: '-noscr'
25/03/2020 08:47:54   Also see the -help entry for tuning parameters.
25/03/2020 08:47:54   You can press 3 Alt_L's (Left "Alt" key) in a row to 
25/03/2020 08:47:54   repaint the screen, also see the -fixscreen option for
25/03/2020 08:47:54   periodic repaints.
25/03/2020 08:47:54 
25/03/2020 08:47:54 XKEYBOARD: number of keysyms per keycode 7 is greater
25/03/2020 08:47:54   than 4 and 51 keysyms are mapped above 4.
25/03/2020 08:47:54   Automatically switching to -xkb mode.
25/03/2020 08:47:54   If this makes the key mapping worse you can
25/03/2020 08:47:54   disable it with the "-noxkb" option.
25/03/2020 08:47:54   Also, remember "-remap DEAD" for accenting characters.
25/03/2020 08:47:54 
25/03/2020 08:47:54 X FBPM extension not supported.
Xlib:  extension "DPMS" missing on display ":0".
25/03/2020 08:47:54 X display is not capable of DPMS.
25/03/2020 08:47:54 --------------------------------------------------------
25/03/2020 08:47:54 
25/03/2020 08:47:54 Default visual ID: 0x21
25/03/2020 08:47:54 Read initial data from X display into framebuffer.
25/03/2020 08:47:54 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
25/03/2020 08:47:54 
25/03/2020 08:47:54 X display :0 is 32bpp depth=24 true color
25/03/2020 08:47:54 
25/03/2020 08:47:54 Listening for VNC connections on TCP port 5900
25/03/2020 08:47:54 
25/03/2020 08:47:54 Xinerama is present and active (e.g. multi-head).
25/03/2020 08:47:54 Xinerama: number of sub-screens: 1
25/03/2020 08:47:54 Xinerama: no blackouts needed (only one sub-screen)
25/03/2020 08:47:54 
25/03/2020 08:47:54 fb read rate: 1404 MB/sec
25/03/2020 08:47:54 fast read: reset -wait  ms to: 10
25/03/2020 08:47:54 fast read: reset -defer ms to: 10
25/03/2020 08:47:54 The X server says there are 10 mouse buttons.
25/03/2020 08:47:54 screen setup finished.
25/03/2020 08:47:54 

The VNC desktop is:      d3cdbabd50f5:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

[services.d] starting openbox...
[openbox] starting...
[services.d] starting logmonitor...
[services.d] starting app...
[logmonitor] no file to monitor: disabling service...
[app] starting JDownloader 2...
[jdsupervisor] JDownloader2 not started yet.  Proceeding...
```
and just hangs here

**Comment by jlesage** [comment] 2020-03-26 00:02
Which error are you talking about ?
