### ISSUE TITLE
Event Scripter capabilities

### ISSUE THREAD

**Issue by benfishbus** [jlesage/docker-jdownloader-2#8] opened 2017-12-28 05:47 UTC
I want to add a script to send a Prowl notification when a package finishes downloading, but doing that - or just about anything useful - in the JDownloader Event Scripter plugin requires calling system binaries like 'curl' which aren't available in the container.  I'm sure this is a basic docker question, but is there a way for me to lightly tweak your container to include additional packages?

**Comment by jlesage** [comment] 2017-12-30 18:28
You can add `curl` package to a running container by executing `docker exec <container name> add-pkg curl`.

However, I guess that useful package can be added to the official image if needed.

Also, did you check if what you want to achieve can be done via the Event Scripter API?

**Comment by benfishbus** [comment] 2018-01-03 06:44
Adding the curl package this way worked - thank you.  I'm guessing that this change will be lost when the container is restarted.  Is there a way to apply it to my copy of the image, so that you don't have to?

I looked into performing this notification directly in Event Scripter, but didn't see any relevant functions in the jdownloader documentation.  I don't know much about regular javascript, but the method I read about for doing HTTP POST (XMLHttpRequest) is not available in Event Scripter.

**Comment by jlesage** [comment] 2018-01-03 18:57
The change would not be lost if container is stopped.  Only when it is removed/re-created.

I found those links which have scripts doing http get/post using the event scripter API.  I guess you should be able to perform your notification with something similar:

https://support.jdownloader.org/Knowledgebase/Article/View/58/0/ifttt-connect-web-services-with-your-jdownloader
https://board.jdownloader.org/showpost.php?p=384496&postcount=36

**Comment by jlesage** [comment] 2018-09-26 15:35
One solution that won't be affected by image updates is to create a small shell script in `/config` that will do the curl call.  The event scripter would call the shell script instead.

The script would be something like this:
```
#!/usr/bin/sh
[ -n "$(which curl)" ] || add-pkg curl
curl [...]
```

**Comment by cbackas** [comment] 2018-09-26 16:14
Hmm... We had tried to include the stuff to run and add the curl package in our shell script but it wasn't working... I'll give it another shot later and let you know if I have any problems

**Comment by jlesage** [comment] 2018-09-26 17:52
Ah yes you are right.  The user used to run JDownloader cannot install packages...

**Comment by cbackas** [comment] 2018-09-26 18:52
So does that mean we can get the curl package added to the docker image? :)

**Comment by benfishbus** [comment] 2018-09-26 18:58
I already had a snippet saved with all the commands to pull, nuke and
rebuild each of my containers and just added the curl install to that. Not
elegant but works 🙂

**Comment by jlesage** [comment] 2018-09-26 19:01
> So does that mean we can get the curl package added to the docker image? :)

Maybe not adding the package directly, but I guess I need to provide an easy way to install it, either via an environment variable or by allowing a user-provided custom init script.

**Comment by cbackas** [comment] 2018-09-26 19:33
Ooh a user-provided customer init script sounds great

**Comment by cbackas** [comment] 2018-11-28 15:56
Hi! @jlesage, any progress on this idea? Would love to get this environment variable ability. 

Thanks

**Comment by jlesage** [comment] 2018-12-04 19:58
This feature will be available with the new baseimage I'm working on. I don't have an ETA but I can say that a good amount of work is already done on it.

**Comment by Mnk3y** [comment] 2020-04-20 11:28
> 
> 
> One solution that won't be affected by image updates is to create a small shell script in `/config` that will do the curl call. The event scripter would call the shell script instead.
> 
> The script would be something like this:
> 
> ```
> #!/usr/bin/sh
> [ -n "$(which curl)" ] || add-pkg curl
> curl [...]
> ```

Currently I'm trying to start a bash script via the Event Scripter. But all the time I get the following error "no such file or directory".

The script is located in the config folder and has the permissions 755.

When I select **File > Load a Link Container** in JDownloader I also see the file in the config folder.

What's the problem? Could someone already start a bash script via the Event Scripter with the Docker version? Thanks.

**Comment by jlesage** [comment] 2020-04-24 02:34
Note that `bash` is not part of the image.  So make sure you script begins with `#!/bin/sh` instead of `#!/bin/bash`.

**Comment by Slomo17** [comment] 2022-11-15 21:23
I know its an old bug report, but i have the same problem as @Mnk3y, whenever i try to test run, it get the error "no such file or directory", when i directly change into the container (docker exec -it jdownloader sh) i can see the file and run it, so it should be there, but the event scripter can't find it for some reason. I also seethe file in jdownloader via load a link container like Mnk3y.
Did you manage to start your script?

**Comment by jlesage** [comment] 2022-11-15 23:43
What are the permissions on the file ?

**Comment by Slomo17** [comment] 2022-11-16 10:46
I change it to 777, but that didn't do the trick. With a jdownloader running locally without docker the script works

**Comment by jlesage** [comment] 2022-11-16 14:35
Can you provide more details so I can reproduce on my side ?  Maybe share your JD script ?

I did a quick test and it works fine for me.

**Comment by Slomo17** [comment] 2022-11-17 17:45
My script looks like this
```

#!/bin/sh

#call filebot
curl "http://filebot:5452/task?id=6"

# clean clutter
find output/Finished/ -iname "*.nfo" -type f -delete
find output/Finished/ -iname "sample" -type d -exec rm -rf {} \;
find output/Finished/ -empty -type d -delete

# Scan to Kodi Database
curl --data-binary '{ "jsonrpc": "2.0", "method": "VideoLibrary.Scan", "id": "mybash"}' -H 'content-type: application/json;' http://[user]:[password]@192.168.178.21:8080/jsonrpc

exit 0
```

**Comment by jlesage** [comment] 2022-11-17 17:54
And how this script is invoked in the JDownloader event scripter ?

**Comment by Slomo17** [comment] 2022-11-17 17:57
var script  = '/Downloads/filebot.sh'
callSync(script)

**Comment by jlesage** [comment] 2022-11-17 19:50
What `docker exec <container name> ls -l /Downloads/filebot.sh` shows ?

**Comment by Slomo17** [comment] 2022-11-17 21:01
I don't know what i did wrong, but now it works. I changed the voulme mapping in docker-compose many times while trying to solve the problem, maybe something got mixed up there.  Thank you very much for your help.

**Comment by jlesage** [comment] 2022-11-18 19:06
Ok great!

I think we can now close this issue.

**Closed by jlesage** 2022-11-18 19:06 UTC
